### PR TITLE
Switch to pytest

### PR DESCRIPTION
**Pull request by phobson**
Also changed python 2.7 testing to just be smoke tests (i.e., no image comparison, just confirm that the functions run)

### CODE REVIEW

**Comment by tacaswell** [comment]
Why did so many test images change?

**Comment by phobson** [comment]
I'm trying to figure that out because I'm seeing a lot of testing inconsistency between platforms and conda environments. 
I'm worried it might be a dependencies from Continuum's channel vs conda-forge. 
Everything that changed did so only very subtly. 




On Wed, May 18, 2016 at 8:48 PM -0700, "Thomas A Caswell" <notifications@github.com> wrote:












Why did so many test images change?

**Comment by janschulz** [comment]
I suspect that this is similar to the problem in mpl where a lot of tests had to put in a small tolerance to let them pass on different systems (windows on appveyor vs linux on travis vs linux on dev machine). Also, the matplotlib packages does not have a stable libfreetype compiled in like the tests in mpl itself. So I think adding a small tolerance is better...

**Comment by tacaswell** [comment]
Looking at the diffs there are some font changes, but it also looks like the markers at the extemas move.

**Pull request merged**
